version = 0.1

[default.deploy.parameters]
stack_name = "lambda-stack"
resolve_s3 = false
s3_prefix = "lambda-stack"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
confirm_changeset = true
